-- AlterTable
ALTER TABLE "GeoCodes" ALTER COLUMN "latitude" SET DEFAULT '0',
ALTER COLUMN "latitude" SET DATA TYPE TEXT,
ALTER COLUMN "longitude" SET DEFAULT '0',
ALTER COLUMN "longitude" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "LocMetrics" ALTER COLUMN "latitude" SET DEFAULT '0',
ALTER COLUMN "latitude" SET DATA TYPE TEXT,
ALTER COLUMN "longitude" SET DEFAULT '0',
ALTER COLUMN "longitude" SET DATA TYPE TEXT;
